[sdk] Update to Gecko SDK 4.2.1
openthread/ot-efr32 pull request #526
Opened 2023-02-23 17:55 UTC by lmnotran

This updates the gecko_sdk submodule to 4.2.1 and also updates the PAL in src/src

# Known Issues
- `crypto.c` changes were not pulled into the ot-efr32 PAL in `src/src`. See the Known Issues of https://github.com/openthread/ot-efr32/pull/482 for more details

2023-02-23 18:06 UTC, hemanth-silabs requested changes
@lmnotran seems like there are some make-pretty issues.

2023-02-23 18:06 UTC, hemanth-silabs commented on src/src/sl_rcp_gp_interface.c
> +/***************************************************************************/ /**
@lmnotran make-pretty issue?

2023-02-23 18:06 UTC, hemanth-silabs commented on src/src/sl_rcp_gp_interface.c
> +    // MAC Frame  : [<---------------MAC Header------------->||<------------------------------------NWK
Same here.

2023-02-23 18:06 UTC, hemanth-silabs commented on src/src/sl_rcp_gp_interface.h
> +/***************************************************************************/ /**
Same

2023-02-23 19:37 UTC, suveshpratapa approved these changes
LGTM

2023-02-23 20:55 UTC, parag-silabs approved these changes
LGTM

2023-02-24 18:20 UTC, bertoldi-silabs approved these changes

2023-02-24 18:35 UTC, hemanth-silabs approved these changes
👍

2023-02-24 21:33 UTC, lmnotran commented
@jwhui can you review this please?

2023-02-27 21:21 UTC, jwhui approved these changes

2023-02-27 21:21 UTC, jwhui commented
@lmnotran , can you help rebase and resolve conflicts?

2023-02-28 04:00 UTC, lmnotran commented
@jwhui Thanks for taking a look at the PR! You should be good to merge now

2023-02-28 05:33 UTC, jwhui approved these changes

2023-02-28 05:34 UTC, merged